<a href="https://colab.research.google.com/github/manik910/Python-practice/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('untitled')

untitled


In [ ]:
print('5+7')

5+7


In [ ]:
a=5
b=7
  print('a+7')

IndentationError: unexpected indent (ipython-input-3574128052.py, line 3)

In [ ]:
a=5
b=10
c=b-a
print(c)

5


In [ ]:
a=[8,7,2,5,]
b=[1,110,2,4,]
c=b-a
print(c)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
a=8 10 110
b=6 200 20
c=b-a
for i in a:
print(c)

SyntaxError: invalid syntax (ipython-input-460366587.py, line 1)

In [ ]:
a=[5,10,3]
for i in a:
  print(i)


5
10
3


In [ ]:
a=[5,b,6]
b=[8,9,7]
for b in a:
  print(b)

5
6
6


In [ ]:
a=(9,8,9)
b(7,8,9)
c=a-b
print(c)


TypeError: 'int' object is not callable

In [ ]:
a=(2+7)
b=(6+8)
c=b-a
print(c)

5


In [ ]:
import calendar as c
month=int(input('enter any month'))
print(c. month(2026,1))

enter any month10
    January 2026
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



In [ ]:
import numpy as np
from numpy import asarray
date=((2,3,4),(3,4,4),(7,8,9))
array=np.asarray(date)
print(array)
print(array.ndim)
print(type(array))

[[2 3 4]
 [3 4 4]
 [7 8 9]]
2
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
date=((2,3),(5,6))
array=np.array(date)
print(array)

[[2 3]
 [5 6]]


In [ ]:
import numpy as np
manik=((5,5),(8,8))
array=np.array(manik)
print(manik)

((5, 5), (8, 8))


In [ ]:
import numpy as np
details = [10, 20, 30, 40, 50]
sales = np.array(details)
print(sales)
print(sales[1])
print(sales[1])
print(sales[2])

[10 20 30 40 50]
20
20
30


In [ ]:
import numpy as np
mani = [10, 20, 30, 40, 50]
sales = np.array(mani)
print(sales)
print(sales[0:])

[10 20 30 40 50]
[10 20 30 40 50]


In [ ]:
import numpy as np
details = [10, 20, 30, 40, 50]
sales = np.array(details)
print(sales)
print(sales[3:])

[10 20 30 40 50]
[40 50]


In [ ]:
import numpy as np
details = [10, 20, 30, 40, 50]
sales = np.array(details)
print(sales)
print(sales[:3])

[10 20 30 40 50]
[10 20 30]


In [ ]:
import numpy as np

matrix = np.array([[22, 20, 46], [40, 50, 70], [70, 80, 100]])

print(matrix)

print(matrix[0,0])
print(matrix[0,1])
print(matrix[0,2])

print(matrix[1,0])
print(matrix[1,1])
print(matrix[1,2])



[[ 22  20  46]
 [ 40  50  70]
 [ 70  80 100]]
22
20
46
40
50
70


In [ ]:
import numpy as np
sales = np.zeros(7)
print(sales)
print(type(sales))

[0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [1]:
import numpy as np
details = np.array([[10, 40, 30], [60, 50, 60]])
sales = np.array(details)
print(sales)
print(sales.shape)

[[10 40 30]
 [60 50 60]]
(2, 3)


In [2]:
import numpy as np

details = [[10, 20, 30], [40, 50, 60]]
sales = np.array(details)
print(sales)

print(sales.T)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]
